### ISSUE TITLE
Publish to private bower and Github enterprise?

### ISSUE THREAD

**Issue by chrisfelix82** [PolymerElements/seed-element#68]
Is there anyway to publish to a private bower registry and Github Enterprise pages instead of the public ones? Is there a project you recomend for hosting private docs and modules for polymer?  I saw el.io but not sure if there is a better one. Thanks.

**Comment by JosefJezek** [comment]
I am working now on fork seed-element-plus. I will add support for private bower and git.

https://github.com/StartPolymer/seed-element-plus

**Comment by JohnRiv** [comment]
@chrisfelix82 just push your individual polymer element repos to your Github Enterprise instance, and then when you're declaring dependencies in your bower.json files, make sure to always specify the org|name/project for the public elements, e.g.
```js
"polymer": "Polymer/polymer#^1.0.0"
```
and for your private elements, specify the path on your Github Enterprise instance:
```js
"my-private-element": "git@YOUR_GHE_SERVER:chrisfelix82/my-private-element.git#^1.0.0"
```
Then you don't need a private bower registry since none of your dependencies require a lookup.

**Comment by chrisfelix82** [comment]
@JohnRiv Thanks for the pointer. I do have a private Bower registry setup now and will publish to it so I can use version tags again instead of the git url.  Now I need to determine if publishing to Github pages for enterprise is possible for the documentation side.

**Comment by ebidel** [comment]
Closing. This is unrelated to the element.
